- tests/AnalyticsTest.php
Don't print out exception if analytics dataset already exists
> Reduce log spam in analytics tests

- tests/TransactionsTest.php
While regular way also works, we acknowledge that this test might be
used as a snippet for examples, or applications. Then if the keyspace
component will accidentally have some special symbol that requires
quoting, the query will fail with parsing error.
To eliminate this type of error, always quote query keyspace.
> always use quoted collection qualifier in transactions tests

- bin/test
The ruby arch might be native arm or emulated mode. Detect either case
> Use RUBY_PLATFORM to detect macos arch

- config.m4
from Remi Collet:
> 5/ bad linker invoked
> 
> The extension is C++ so should be link using g++, not gcc
> 
> -  PHP_NEW_EXTENSION(couchbase, ${COUCHBASE_FILES}, $ext_shared)
> +  PHP_NEW_EXTENSION(couchbase, ${COUCHBASE_FILES}, $ext_shared,,, cxx)
> 
> This will create issue for people using some specific versions,
> to properly add needed libraries (libstdc++)
> 
> Example when using devtoolset on RHEL/CentOS to have a modern GCC
> (libstdc++ is a static library, only added when g++ is invoked)
> use C++ linker for the extension

- bin/update-package-xml
- package.xml
from Remi Collet
> 4/ missing documentation
> 
> Lot of files, especially all LICENSE* and COPYING* should
> have role="doc" to be installed
> properly mark documentation in package.xml

- src/wrapper/core_error_info.hxx
This is not enough, the same header needs to be added in a lot of files in deps:
- src/deps/couchbase-cxx-client/core/error_context/analytics.hxx
- src/deps/couchbase-cxx-client/core/error_context/http.hxx
- src/deps/couchbase-cxx-client/core/error_context/query.hxx
- src/deps/couchbase-cxx-client/core/error_context/search.hxx
- src/deps/couchbase-cxx-client/core/error_context/view.hxx
- src/deps/couchbase-cxx-client/core/impl/subdoc/lookup_in_macro.cxx
- src/deps/couchbase-cxx-client/core/impl/subdoc/mutate_in_macro.cxx
- src/deps/couchbase-cxx-client/core/operations/management/analytics_problem.hxx
- src/deps/couchbase-cxx-client/core/operations/management/eventing_problem.hxx
- src/deps/couchbase-cxx-client/core/platform/base64.cc
- …
> Fix missing header for GCC 13

- Couchbase/QueryOptions.php
- package.xml
- src/wrapper/conversion_utilities.cxx
- src/wrapper/transaction_context_resource.cxx
This one update core to pickup GCC-13 fixes. Also it happened that query_context changes has been merged to the core already. While it touches related places in PHP sources, it does not implement any of planned changes to query management API, which will come later.
> update core to 1.0.0-beta.5

- tests/QueryTest.php
in fact query engine started returning different error code for this kind of user error, but in particular case it does not matter, and matching for error text is enough here.
Old error code was `(3000, IKey: "parse.syntax_error")`, mapped to `ParsingFailureException`, while new code is `(3080, IKey: "formalize.ambiguous_reference")`
> relax requirement of the test

- package.xml
- src/wrapper/connection_handle.cxx
Notable changes:
* CXXCBC-31: Allow to use schema-less connection strings (#394)
* CXXCBC-318: Always try TCP if UDP fails in DNS-SRV resolver (#390)
* CXXCBC-320: Negative expiry in atr can 'stuck' docs. (#393)
* CXXCBC-310: Improve shutdown of the LostTxnCleanup thread. (#389)
> update C++ core

- src/wrapper/common.hxx
4.1.5 + this patch builds fine (not tested)
> zend_bool was removed from 8.3

- Couchbase/Management/BucketSettings.php
- Couchbase/Management/CollectionManager.php
- Couchbase/Management/CollectionSpec.php
- Couchbase/Management/CreateCollectionSettings.php
- Couchbase/Management/ScopeSpec.php
- Couchbase/Management/UpdateCollectionOptions.php
- Couchbase/Management/UpdateCollectionSettings.php
- src/php_couchbase.cxx
- src/wrapper/connection_handle.cxx
- src/wrapper/connection_handle.hxx
- tests/BucketManagerTest.php
- tests/CollectionManagerTest.php
- tests/Helpers/ServerVersion.php
Changes: 
- Implemented Bucket No dedup feature in collection and bucket manager
- Deprecated old API for CreateCollection & DropCollection
> PCBC-950: Support bucket settings for no dedup feature

- src/php_couchbase.cxx
- src/wrapper/connection_handle.cxx
- src/wrapper/connection_handle.hxx
- src/wrapper/logger.cxx
- src/wrapper/logger.hxx
* the wrapper should wait until the core connection is closed in order to ensure that the in-flight operations will not use any invalid resources
* shutdown logger when the module is being unloaded
> PCBC-964: wait until the core connection is closed

- Couchbase/Cluster.php
- Couchbase/SearchOptions.php
- Couchbase/SearchRequest.php
- Couchbase/VectorQuery.php
- Couchbase/VectorQueryCombination.php
- Couchbase/VectorSearch.php
- Couchbase/VectorSearchOptions.php
- package.xml
- src/php_couchbase.cxx
- src/wrapper/connection_handle.cxx
- src/wrapper/connection_handle.hxx
- src/wrapper/conversion_utilities.cxx
- src/wrapper/conversion_utilities.hxx
- tests/SearchTest.php
Changes:
- Updated C++ Core
- Add support for Vector search & Cluster::search() API
- Add testing
> PCBC-967 Support for vector search

- Couchbase/DecrementOptions.php
In v4.1.6, the following code piece will fail when executed:
```php
<?php
// ...
$options = new Couchbase\DecrementOptions();
$options->initial(1);
$options->expiry((new DateTimeImmutable())->modify('+5 seconds'));
$collection->binary()->decrement($key, $options);
?>
```
The error message looks like the following:
> Warning: Object of class DateTimeImmutable could not be converted to int in vendor/couchbase/couchbase/Couchbase/DecrementOptions.php on line 123
> add missing use statement in class DecrementOptions

- Couchbase/Cluster.php
- Couchbase/Management/ScopeSearchIndexManager.php
- Couchbase/Management/ScopeSearchIndexManagerInterface.php
- Couchbase/Scope.php
- Couchbase/ScopeInterface.php
- package.xml
- src/php_couchbase.cxx
- src/wrapper/connection_handle.cxx
- src/wrapper/connection_handle.hxx
- src/wrapper/conversion_utilities.cxx
- tests/Helpers/ServerVersion.php
- tests/SearchIndexManagerTest.php
- tests/SearchTest.php
Changes: 
- Add support for scope.Search()
- Add ScopeSearchIndexManager
> PCBC-970 SDK Support for Scoped Search Indexes

- Couchbase/BooleanFieldSearchQuery.php
- Couchbase/BooleanSearchQuery.php
- Couchbase/ConjunctionSearchQuery.php
- Couchbase/DateRangeSearchQuery.php
- Couchbase/DisjunctionSearchQuery.php
- Couchbase/DocIdSearchQuery.php
- Couchbase/GeoBoundingBoxSearchQuery.php
- Couchbase/GeoDistanceSearchQuery.php
- Couchbase/MatchAllSearchQuery.php
- Couchbase/MatchNoneSearchQuery.php
- Couchbase/MatchPhraseSearchQuery.php
- Couchbase/MatchSearchQuery.php
- Couchbase/NumericRangeSearchQuery.php
- Couchbase/PhraseSearchQuery.php
- Couchbase/PrefixSearchQuery.php
- Couchbase/QueryStringSearchQuery.php
- Couchbase/RegexpSearchQuery.php
- Couchbase/SearchRequest.php
- Couchbase/TermRangeSearchQuery.php
- Couchbase/TermSearchQuery.php
- Couchbase/WildcardSearchQuery.php
Changes:
- Add static helpers to SearchQueries, particularly useful for chaining with cluster/scope.search() API
> PCBC-979 Add static helpers to SearchQuery types

- .gitignore
- Couchbase/Cluster.php
- composer.json
Hard dependency on gRPC in PHP might be problematic, so by relaxing the requirement we allow users to choose whether to install gRPC and instead check its presence runtime and throw exception if couchbase2:// protocol is being used while the extensions are not loaded.
> PCBC-969: move grpc dependencies to suggests section

- tests/KeyValueLockingTest.php
update in test PessimisticLocking, check if CAS value before document locked is same as CAS value after the document gets unlocked
> update in test PessimisticLocking

- .github/workflows/tests.yml
- .gitignore
- bin/test.rb
- compile_commands.json
- config.w32
- src/wrapper/connection_handle.cxx
- src/wrapper/logger.cxx
- tests/AnalyticsTest.php
- tests/BucketManagerTest.php
- tests/CollectionManagerTest.php
- tests/Helpers/Caves.php
- tests/Helpers/CouchbaseTestCase.php
- tests/KeyValueBinaryOperationsTest.php
- tests/KeyValueCounterTest.php
- tests/KeyValueGetTest.php
- tests/KeyValueMultiOperationsTest.php
- tests/KeyValueRemoveTest.php
- tests/KeyValueReplaceTest.php
- tests/KeyValueScanTest.php
- tests/KeyValueTouchingTest.php
- tests/SearchTest.php
- tests/UserManagerTest.php
- tests/beer-search.json
Also fixes tests failures reported in PCBC-980
> PCBC-859: configure Github Actions for Windows

- Couchbase/VectorQuery.php
- tests/Helpers/CouchbaseTestCase.php
- tests/SearchTest.php
Changes:
- Added support for base_64 encoded vector types
> PCBC-994 Support for base64 encoded vector types

- Couchbase/VectorQuery.php
- Couchbase/VectorSearch.php
Changes
- Added InvalidArguments check for vector search
- Improved codedoc regarding base64-encoded vector queries
> PCBC-995: The SDK should throw an InvalidArgumentException when an empty VectorSearch is constructed

- .gitattributes
Exclude C++ files, tests and development scripts, so that Packagist will not install them to the application ./vendor directory.
> PCBC-997: Do not export development files

- src/php_couchbase.cxx
> PCBC-1009: do not use IS_RESOURCE in function signatures

- Couchbase/SearchQuery.php
Changes:
- Updated SearchQuery API link to current
> PCBC-1011: SearchQuery link in API doc is broken

- src/wrapper/connection_handle.cxx
This should fix https://jira.issues.couchbase.com/browse/PCBC-975. It seems like the call to set the expiry was just missing for no obvious reason.
> PCBC-975 : Fix expiry with upsertMulti

- src/php_couchbase.cxx
- src/wrapper/persistent_connections_cache.cxx
In some cases, when the extension is configured aggressively close persistent connections (e.g. with `couchbase.max_persistent=0` and `couchbase.persistent_timeout=0`), the connections might be considered expired and scheduled for destruction even if the application has references to them.
This patch changes this behavior to skip such connection, and destroy them later, when the reference counter reaches zero.
> PCBC-1018: Do not destroy expired connection if it still being used

- MIGRATION_FROM_3_x.md
This patch is related to [DOC-12803](https://jira.issues.couchbase.com/browse/DOC-12803). It documents INI options related to persistent connections.
More info about the concept is here: https://www.php.net/manual/en/features.persistent-connections.php
[DOC-12803]: https://couchbasecloud.atlassian.net/browse/DOC-12803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add note about persistent connections

- Couchbase/TransactionAttemptContext.php
- Couchbase/TransactionGetOptions.php
- Couchbase/TransactionGetResult.php
- Couchbase/TransactionInsertOptions.php
- Couchbase/TransactionReplaceOptions.php
- src/php_couchbase.cxx
- src/wrapper/transaction_context_resource.cxx
- src/wrapper/transaction_context_resource.hxx
- tests/Helpers/ServerVersion.php
- tests/TransactionsTest.php
Changes:
- Added Options w/ Transcoder for Transactions Insert, Replace, Get, and GetReplica
- Updated core to use specified transcoder flags
> PCBC-993: Support Binary Objects in Transactions

- src/php_couchbase.cxx
- src/wrapper/common.cxx
- src/wrapper/common.hxx
Changes:
- Update core to pick up Analytics 2.0 connection prevention
> PCBC-1027: Operational SDK prevent connection to Analytics 2.0 Cluster

- Couchbase/Collection.php
- Couchbase/Utilities/ExpiryHelper.php
- tests/ExpiryTest.php
Motivation
-----------
The Server expects that expiry set to >= 30 days is given as an absolute timestamp
Changes
---------
Adds `parseExpiry` function which converts expiry into a form the server expects, and validates it
> PCBC-1030: Fix how SDK handles KV Expiry
