- README.md
- bin/build
Main changes:
- Small fix required to build on modern MacOS.
- More complete README with instructions.
> Fixing some build problems that were discovered during testing

- README.md
> Removing boost from README.

- bin/update-package-xml
- package.xml
from Remi Collet
> 3/ missing LICENSE
> 
> For the extension
> fix license in package.xml

- src/wrapper/conversion_utilities.cxx
- src/wrapper/transactions_resource.cxx
Update core with srv refresh fix for timeout error during bootstrap + fix wrapper for query methods api change
> update core and wrapper

- src/wrapper/logger.cxx
workaround API constification for php7 (https://github.com/php/php-src/commit/88355dd338835f7a59415ecb2e7e970658f3867f)
> fix build with php < 8

- src/Couchbase/Protostellar/Collection.php
- src/Couchbase/Protostellar/Internal/KVConverter.php
- src/Couchbase/Protostellar/Internal/QueryConverter.php
- src/Couchbase/Protostellar/Internal/SharedUtils.php
API completed, but as it is not completely implemented in the gateway, will need to be verified as part of [PCBC-892](https://issues.couchbase.com/browse/PCBC-892)
> Implement lookupin/mutatein

- src/Couchbase/Protostellar/Cluster.php
- src/Couchbase/Protostellar/Internal/Client.php
- src/Couchbase/Protostellar/Internal/QueryConverter.php
- src/Couchbase/Protostellar/Internal/SearchConverter.php
The SearchResponse is not yet implemented in PS, so will have done under another ticket
> PCBC-896 Implementing search client - SearchRequest implemented

- src/Couchbase/Protostellar/Bucket.php
- src/Couchbase/Protostellar/Internal/Client.php
- src/Couchbase/Protostellar/Internal/CollectionManagementConverter.php
- src/Couchbase/Protostellar/Management/CollectionManager.php
Implemented collection management implemented in PS, testing will be added under [PCBC-892](https://issues.couchbase.com/browse/PCBC-892) due to current STG authentication issue
> PCBC-911 Implement collection manager

- src/Couchbase/Protostellar/Cluster.php
- src/Couchbase/Protostellar/Internal/BucketManagementConverter.php
- src/Couchbase/Protostellar/Internal/Client.php
- src/Couchbase/Protostellar/Management/BucketManager.php
Testing to be implemented under PCBC-892 due to STG authentication issue
> PCBC-910 Implement bucket manager

- src/Couchbase/Protostellar/Internal/Client.php
- src/Couchbase/Protostellar/Internal/ExceptionConverter.php
- src/Couchbase/Protostellar/Internal/KVConverter.php
- src/Couchbase/Protostellar/ProtostellarRequest.php
- Fixed bug with channel not accepting the options
- Added timeout support to error handling, in the case where there is a GRPC deadline exceeded returned from the server
- Updated expiry to be in line with recent PS changes
> Small PS fixes

- Couchbase/Collection.php
- Couchbase/LookupInAllReplicasOptions.php
- Couchbase/LookupInAnyReplicaOptions.php
- Couchbase/LookupInReplicaResult.php
- package.xml
- src/php_couchbase.cxx
- src/wrapper/connection_handle.cxx
- src/wrapper/connection_handle.hxx
- tests/Helpers/ServerVersion.php
- tests/KeyValueLookupInTest.php
Changes:
- Update CXX core
- Expose subdoc replica read functions to wrapper
- Add tests
> PCBC-940 Support for subdoc read from replica

- package.xml
- src/wrapper/connection_handle.cxx
Changes: 
- Update C++ Core
- Update wrapper conversion to use new BucketSettings optional fields
> PCBC-956 Update wrapper side bucket settings

- src/Couchbase/Protostellar/Cluster.php
- src/Couchbase/Protostellar/Internal/Client.php
- src/Couchbase/Protostellar/Internal/SearchIndexManagementRequestConverter.php
- src/Couchbase/Protostellar/Internal/SearchIndexManagementResponseConverter.php
- src/Couchbase/Protostellar/Management/SearchIndexManager.php
- tests/SearchIndexManagerTest.php
Changes:
- Implemented Search admin client & conversion methods
- Imported classic tests
> PCBC-933 Protostellar: Implement search admin client

- Couchbase/Management/CreateCollectionSettings.php
- Couchbase/Management/UpdateCollectionSettings.php
- package.xml
- tests/CollectionManagerTest.php
- tests/Helpers/ServerVersion.php
Changes 
- Added check for valid collection maxTTL value
- Added testing
> PCBC-968 Support for maxTTL value of -1 for collection "no expiry"

- Couchbase/Management/CollectionQueryIndexManager.php
- Couchbase/Management/QueryIndexManager.php
- src/php_couchbase.cxx
- src/wrapper/connection_handle.cxx
- src/wrapper/connection_handle.hxx
- src/wrapper/scan_result_resource.cxx
Changes:
- Update C++ Core to pick up Index key encoding and Cluster capability search check 
- Rename Query Index Create fields -> keys
> PCBC-871, PCBC-976 & PCBC-953 Create Index Key Encoding, FeatureNotAvailable for new Search Capabilities and 0xd config update

- Couchbase/Cluster.php
- Couchbase/Collection.php
- Couchbase/Management/ScopeSearchIndexManager.php
- Couchbase/Scope.php
- Couchbase/SearchRequest.php
- Couchbase/VectorQuery.php
- Couchbase/VectorSearch.php
- Couchbase/VectorSearchOptions.php
Changes:
- Bumped Stability levels:
- Couchbase2:// -> Uncomitted
- Range Scan -> Committed
- Scoped Search Indexes -> Committed
- Vector Search -> Uncommitted
> PCBC-982: SDK 3.5 Release Prep Stability levels

- Couchbase/Management/SearchIndex.php
- Couchbase/Management/SearchIndexManager.php
- tests/BucketManagerTest.php
- tests/Helpers/ServerVersion.php
- tests/QueryIndexManagerTest.php
- tests/SearchTest.php
- tests/beer-search.json
* improve diagnostics
* update feature detection
* ensure that index for beer-sample is loaded before the test run
> Cleanup tests

- tests/BucketManagerTest.php
- tests/CollectionManagerTest.php
- tests/Helpers/ConsistencyUtils.php
- tests/Helpers/CouchbaseTestCase.php
- tests/Helpers/TestEnvironment.php
- tests/KeyValueLookupInTest.php
- tests/QueryIndexManagerTest.php
- tests/SearchTest.php
- tests/UserManagerTest.php
- tests/ViewTest.php
Changes:
- Added consistency utility, which polls every node to ensure resources are updated
> PCBC-991 Add consistency utility for testing

- src/wrapper/connection_handle.cxx
the extension was matching option name incorrectly, and essentially skipping the options
> PCBC-1016: fix trustCertificate option

- Couchbase/Cluster.php
> Fix Undefined Error

- Couchbase/AppendOptions.php
- Couchbase/PrependOptions.php
- src/wrapper/connection_handle.cxx
- tests/KeyValueBinaryOperationsTest.php
Changes:
- Add CAS to AppendOptions & PrependOptions
- Update C++ Core
> PCBC-1025: Add CAS to Append and Prepend

- Couchbase/BooleanFieldSearchQuery.php
- Couchbase/BooleanSearchQuery.php
- Couchbase/ConjunctionSearchQuery.php
- Couchbase/DateRangeSearchQuery.php
- Couchbase/DisjunctionSearchQuery.php
- Couchbase/DocIdSearchQuery.php
- Couchbase/GeoBoundingBoxSearchQuery.php
- Couchbase/GeoDistanceSearchQuery.php
- Couchbase/GeoPolygonQuery.php
- Couchbase/MatchAllSearchQuery.php
- Couchbase/MatchNoneSearchQuery.php
- Couchbase/MatchPhraseSearchQuery.php
- Couchbase/MatchSearchQuery.php
- Couchbase/NumericRangeSearchQuery.php
- Couchbase/PhraseSearchQuery.php
- Couchbase/PrefixSearchQuery.php
- Couchbase/QueryStringSearchQuery.php
- Couchbase/RegexpSearchQuery.php
- Couchbase/SearchQuery.php
- Couchbase/TermRangeSearchQuery.php
- Couchbase/TermSearchQuery.php
- Couchbase/VectorQuery.php
- Couchbase/WildcardSearchQuery.php
- tests/SearchTest.php
Changes:
- Implement Vector search pre-filters
- Refactored SearchQuery interface for easier JSON serialization
> PCBC-1026: Support FTS like Pre-Filters while doing Vector Search
